### ISSUE TITLE
xtensor pragma use

### ISSUE THREAD

**Issue by DavisVaughan** [QuantStack/Xtensor.R#11]
I've noticed this note in the past. Did CRAN bless this as being alright? Not sure if there is anything you can do about it anyways since I'm guessing you need it in core xtensor, but just wanted to ask.

```
Version: 0.9.0-0 
Check: pragmas in C/C++ headers and code 
Result: NOTE 
    File which contains pragma(s) suppressing diagnostics:
     ‘inst/include/xtensor/xstorage.hpp’ 
```

**Comment by SylvainCorlay** [comment]
Yes, we have generally made the answer to CRAN, and everytime, they accepted the package an dismissed the note:

*The submission to CRAN seems to be rejected automatically over the following NOTE:*

```
* checking pragmas in C/C++ headers and code ... NOTE File which containspragma(s) suppressing diagnostics:
  ‘inst/include/xtensor/xstorage.hpp’
```

*The xstorage.hpp file in xtensor adds a pragma and removes it in the end of the file, to prevent an incorrect warning to be triggered by GCC8:*

```
// The C++ standard defines tuple_size as a class, however
// G++ 8 C++ library does define it as a struct hence we get
// clang warnings here
#if defined(__clang__)
    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wmismatched-tags"
#endif
{
   [...]
}
#if defined(__clang__)
    #pragma clang diagnostic pop
#endif
```

*In our opinion, this is the correct way to deal with this compiler bug and we actually pop the diagnostic pragma that we pushed after the code triggering it. Hence I don't think that this NOTE should be a blocker for the latest release of xtensor to be accepted on CRAN.*

**Comment by DavisVaughan** [comment]
Sounds good! Just wanted to make sure
